name: Run Pragma Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-pragma:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Pragma Custom Action
        uses: Silverlan/test_ci2/github_actions/test@main  # This points to the root directory of your repository where action.yml is located
        with:
          lua-code: |
            local test = "Hello"
            print(test)
